# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable updates to github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
