#! /bin/sh
# see example at https://github.com/HaddingtonDynamics/updaterobot

VERSION='v2022.07.28'


scp -r https://github.com/cfry/dde/archive/refs/heads/dde4.zip ~dde4dde_temp

#get url from the dde4 git page, CODE (big green() menu, copy Link
curl -v -L -o ddex.zip https://github.com/cfry/dde/archive/refs/heads/master.zip

https://github.com/cfry/dde/tree/dde4/dde

